/* A Bison parser, made by GNU Bison 2.3.  */

/* Skeleton interface for Bison's Yacc-like parsers in C

   Copyright (C) 1984, 1989, 1990, 2000, 2001, 2002, 2003, 2004, 2005, 2006
   Free Software Foundation, Inc.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street, Fifth Floor,
   Boston, MA 02110-1301, USA.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* Tokens.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
   /* Put the tokens into the symbol table, so that GDB and other debuggers
      know about them.  */
   enum yytokentype {
     T_DIGIT = 258,
     T_FLOAT = 259,
     T_ID = 260,
     T_Boolean = 261,
     T_FUNC = 262,
     T_RETURN = 263,
     T_ADD = 264,
     T_SUB = 265,
     T_MUL = 266,
     T_DIV = 267,
     T_REM = 268,
     T_EQ = 269,
     T_NE = 270,
     T_LE = 271,
     T_LN = 272,
     T_GE = 273,
     T_GN = 274,
     T_LAND = 275,
     T_LOR = 276,
     T_IF = 277,
     T_ELSE = 278,
     T_WHILE = 279,
     T_BREAK = 280,
     T_CONTINUE = 281,
     T_GOTO = 282,
     T_VOID = 283,
     E_IF = 284,
     T_CONST = 285,
     INT = 286,
     FLOAT = 287,
     T_POINTER = 288,
     T_NOT = 289
   };
#endif
/* Tokens.  */
#define T_DIGIT 258
#define T_FLOAT 259
#define T_ID 260
#define T_Boolean 261
#define T_FUNC 262
#define T_RETURN 263
#define T_ADD 264
#define T_SUB 265
#define T_MUL 266
#define T_DIV 267
#define T_REM 268
#define T_EQ 269
#define T_NE 270
#define T_LE 271
#define T_LN 272
#define T_GE 273
#define T_GN 274
#define T_LAND 275
#define T_LOR 276
#define T_IF 277
#define T_ELSE 278
#define T_WHILE 279
#define T_BREAK 280
#define T_CONTINUE 281
#define T_GOTO 282
#define T_VOID 283
#define E_IF 284
#define T_CONST 285
#define INT 286
#define FLOAT 287
#define T_POINTER 288
#define T_NOT 289




#if ! defined YYSTYPE && ! defined YYSTYPE_IS_DECLARED
typedef union YYSTYPE
#line 43 "/Users/zzh/compiler/April/calculator/frontend/flexbison/Calculator.y"
{
    class ast_node * node;

    struct digit_int_attr integer_num;
    struct digit_real_attr float_num;
    struct var_id_attr var_id;
	struct digit_bool_attr bool_num;
}
/* Line 1529 of yacc.c.  */
#line 126 "/Users/zzh/compiler/April/calculator/frontend/flexbison/autogenerated/CalculatorBison.h"
	YYSTYPE;
# define yystype YYSTYPE /* obsolescent; will be withdrawn */
# define YYSTYPE_IS_DECLARED 1
# define YYSTYPE_IS_TRIVIAL 1
#endif

extern YYSTYPE yylval;

